<a href="https://colab.research.google.com/github/atharvthakur17/machine-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1,2], [3,4],[5, 6], [7,8]])
print(a)
a.reshape((2,4))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a=np.array([1,3,4,6,8,6])
print(a)
b=np.arange(6)+7
print(b)
a.dot(b)
np.dot(a,b)



[1 3 4 6 8 6]
[ 7  8  9 10 11 12]


287

In [ ]:
a=np.zeros((3,3))
a[:,2]=2
print(a)
b=np.eye(3)
print(b)


[[0. 0. 2.]
 [0. 0. 2.]
 [0. 0. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a)
print(b)
import math as m
d=m.sqrt(sum((a-b)**2))                 #dist sq pronlem
print(d)

[1 2 3]
[5 6 7]
6.928203230275509


In [ ]:
#how far point from mean 
a=np.array([1,3,5,6])
f=((a-a.mean())**2).sum()
print(f)

14.75


In [63]:
#random matrix
a=np.random.random((2,4))
print(a)
a=np.array([1,3,5,6])
b=np.array([3,6,8,4])
#stacking
c=np.stack((a,b),axis=0)
print(c)
print(c.shape)

c=np.stack((a,b),axis=1)
print(c)
c.shape

[[0.87091221 0.01839073 0.18277087 0.09009996]
 [0.57747205 0.70709551 0.4536179  0.80633177]]
[[1 3 5 6]
 [3 6 8 4]]
(2, 4)
[[1 3]
 [3 6]
 [5 8]
 [6 4]]


(4, 2)

In [67]:
a=np.random.rand(2,3)
b=np.random.randn(2,3)
c=np.random.randint(2,8,4)   #no. of int value from given range
print(a)
print(b)
print(c)


[[0.77872196 0.73145222 0.01138501]
 [0.02500541 0.16364603 0.23837837]]
[[ 2.62822534 -1.29327135 -1.73887282]
 [-0.99474701 -0.82118769  0.7724892 ]]
[7 3 5 2]
